services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:latest
    environment:
      - DB_HOST=ep-broad-hat-acpgq3im-pooler.sa-east-1.aws.neon.tech
      - DB_PORT=5432
      - DB_USERNAME=alfresco_owner
      - DB_PASSWORD=npg_4AlVsG8rcBak
      - DB_NAME=alfresco
      - JAVA_OPTS=-Xms2G -Xmx2G
    ports:
      - "8080:8080"
    depends_on:
      - alfresco-db
    networks:
      - alfresco-network

  alfresco-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=alfresco_owner
      - POSTGRES_PASSWORD=npg_4AlVsG8rcBak
      - POSTGRES_DB=alfresco
    networks:
      - alfresco-network

networks:
  alfresco-network:
    driver: bridge
